version: '3'
services:
  user-service:
    # blue env (live version)
    image: 881490135288.dkr.ecr.eu-north-1.amazonaws.com/user-service:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  user-service-green:
    # green env (test version)
    image: 881490135288.dkr.ecr.eu-north-1.amazonaws.com/user-service:latest
    ports:
      - "3002:3001"
    environment:
      - NODE_ENV=production